---
name: Rust Testing
"on":
  push:
  pull_request:
env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  cargo_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install dependencies
        run: brew install dav1d libheif
      - uses: extractions/setup-just@v3

      - name: "Run cargo test with coverage"
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          cargo install cargo-tarpaulin
          just coveralls
        if: github.actor != 'dependabot[bot]'
      - name: "Run cargo test without coverage"
        run: |
          cargo test --workspace --all-features
        if: github.actor != 'dependabot[bot]'
      - name: "Build the workspace (release)"
        run: cargo build --workspace --release
      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats
